version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "12:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.7.0
    - 7.8.0
  - dependency-name: "@vue/cli-plugin-unit-jest"
    versions:
    - 4.5.11
  - dependency-name: csv-parse
    versions:
    - 4.15.3
  - dependency-name: "@fortawesome/free-solid-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: core-js
    versions:
    - 3.8.3
    - 3.9.0
  - dependency-name: marked
    versions:
    - 1.2.7
    - 1.2.8
  - dependency-name: "@vue/cli-plugin-pwa"
    versions:
    - 4.5.11
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.2
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: vue-meta
    versions:
    - 2.4.0
  - dependency-name: vue-router
    versions:
    - 3.4.9
