backend:
  name: github
  repo: gabedunn/canmore-brewing
  branch: master

site_url: https://canmorebrewing.com

media_library:
  name: cloudinary
  config:
    cloud_name: canmore-brewing-company
    api_key: 885415494169291

collections:
  - label: Content
    name: Content
    files:
      - label: Notification Banner
        name: notification
        file: src/assets/content/notification.json
        fields:
          - { label: Enabled, name: enabled, widget: boolean }
          - label: Colour
            name: colour
            hint: Background colour for the notiofication banner.
            widget: select
            options:
              - { label: White, value: white }
              - { label: Gray, value: gray }
              - { label: Pink, value: pink }
              - { label: Red, value: red }
              - { label: Orange, value: orange }
              - { label: Yellow, value: yellow }
              - { label: Green, value: green }
              - { label: Teal, value: teal }
              - { label: Blue, value: blue }
              - { label: Indigo, value: indigo }
              - { label: Purple, value: purple }
          - { label: Title, name: title, widget: string }
          - { label: Subtitles, name: subtitle, widget: list, field: { label: Line, name: line, widget: string } }
          - { label: Content, name: content, widget: string }
          - { label: Enable Button, name: button_status, widget: boolean }
          - { label: Button Text, name: button, widget: list, required: false, field: { label: Line, name: line, widget: string } }
          - { label: Button URL, name: url, widget: string, required: false }
      - label: Beers
        name: beers
        file: src/assets/content/beers.json
        fields:
          - label: Core Beers
            name: core
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Description, name: description, widget: markdown }
              - { label: Alcohol by Volume, name: abv, widget: number, valueType: float, min: 0, step: 0.1 }
              - { label: IBU, name: ibu, widget: number, valueType: int, min: 0, step: 1 }
              - { label: SRM, name: srm, widget: number, valueType: int, min: 0, step: 1 }
              - { label: Logo, name: logo, widget: image }
              - { label: Can Image, name: can, widget: image }
              - { label: Background Colour, name: bg, widget: string, hint: Hex code for the colour. }
              - label: Text Colour
                name: textColour
                widget: select
                options:
                  - { label: Black, value: black }
                  - { label: White, value: white }
                default: black
                hint: Contrast to the background colour.
          - label: Seasonal Beers
            name: seasonal
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Description, name: description, widget: markdown }
              - { label: Alcohol by Volume, name: abv, widget: number, valueType: float, min: 0, step: 0.1 }
              - { label: IBU, name: ibu, widget: number, valueType: int, min: 0, step: 1 }
              - { label: SRM, name: srm, widget: number, valueType: int, min: 0, step: 1 }
              - { label: Logo, name: logo, widget: image }
              - { label: Can Image, name: can, widget: image }
              - { label: Background Colour, name: bg, widget: string, hint: Hex code for the colour. }
              - label: Text Colour
                name: textColour
                widget: select
                options:
                  - { label: Black, value: black }
                  - { label: White, value: white }
                default: black
                hint: Contrast to the background colour.
      - label: Fallback Hours
        name: hours
        file: src/assets/content/hours.json
        fields:
          - label: Monday
            name: monday
            widget: object
            fields:
              - { label: Hours, name: hours, widget: string }
              - { label: Closed, name: closed, widget: boolean, required: false, default: false }
          - label: Tuesday
            name: tuesday
            widget: object
            fields:
              - { label: Hours, name: hours, widget: string }
              - { label: Closed, name: closed, widget: boolean, required: false, default: false }
          - label: Wednesday
            name: wednesday
            widget: object
            fields:
              - { label: Hours, name: hours, widget: string }
              - { label: Closed, name: closed, widget: boolean, required: false, default: false }
          - label: Thursday
            name: thursday
            widget: object
            fields:
              - { label: Hours, name: hours, widget: string }
              - { label: Closed, name: closed, widget: boolean, required: false, default: false }
          - label: Friday
            name: friday
            widget: object
            fields:
              - { label: Hours, name: hours, widget: string }
              - { label: Closed, name: closed, widget: boolean, required: false, default: false }
          - label: Saturday
            name: saturday
            widget: object
            fields:
              - { label: Hours, name: hours, widget: string }
              - { label: Closed, name: closed, widget: boolean, required: false, default: false }
          - label: Sunday
            name: sunday
            widget: object
            fields:
              - { label: Hours, name: hours, widget: string }
              - { label: Closed, name: closed, widget: boolean, required: false, default: false }
    editor:
      preview: false
